import os
from datetime import datetime

def generate_plan(file_path: str) -> str:
    """
    Generates a Plan.md file in the Plans/ directory based on the input document.
    Returns the path to the generated plan file.
    """
    try:
        with open(file_path, "r", encoding="utf-8") as f:
            document_content = f.read()

        file_name = os.path.basename(file_path)
        plan_title = f"Plan for {os.path.splitext(file_name)[0]}"
        plan_filename = os.path.join("Plans", f"{plan_title.replace(' ', '_')}.md")

        plan_content = f"""# {plan_title}

## Generated Date
{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

## Source Document
{file_name}

## Document Content
```
{document_content}
```

## Proposed Plan (AI Generated)
1. Analyze the core request from the document.
2. Identify key objectives.
3. Break down objectives into actionable steps.
4. Assign responsibilities (if applicable).
5. Set deadlines.
6. Outline potential roadblocks and solutions.

---
*This plan was automatically generated by the AI Employee Vault.*
"""
        os.makedirs("Plans", exist_ok=True) # Ensure Plans directory exists
        with open(plan_filename, "w", encoding="utf-8") as f:
            f.write(plan_content)

        print(f"[PLAN GENERATOR]: Generated plan for '{file_name}' at '{plan_filename}'")
        return plan_filename

    except Exception as e:
        print(f"[PLAN GENERATOR ERROR]: Could not generate plan for {file_name}. Error: {e}")
        return ""
